on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          repository: m161awm2/cicd-practice
      - name: set up node-js/nestjs
        uses: actions/setup-node@v3
        with:
          node-version: 20
      - name: run code
        run: |
          npm ci
          npm start